export const onboardingAgreementText = {
  ro: {
    loading: "Verificăm documentele deja semnate…",
    unavailable: "Nu am putut verifica documentele semnate. Reîncearcă înainte de a trimite înscrierea.",
    retry: "Reîncearcă verificarea",
    title: "Continuă cu acordul deja semnat",
    intro: "Semnătura ta a fost salvată. Înscrierea va continua pe baza documentelor de mai jos, fără o nouă semnătură. Datele juridice și limba contractului rămân cele de la semnare, chiar dacă ai schimbat limba site-ului.",
    correction: "Datele de mai jos nu pot fi modificate aici. Dacă persoana sau entitatea juridică, identificatorul, adresa ori reprezentantul sunt greșite, nu trimite înscrierea și contactează administratorul pentru corectare.",
    contact: "Contactează administratorul",
    party: "Persoana / entitatea juridică",
    kind: "Tipul părții",
    individual: "Persoană fizică",
    sole_trader: "Întreprinzător individual",
    company: "Persoană juridică",
    identifier: "IDNP / IDNO",
    address: "Adresa juridică",
    representative: "Reprezentant",
    role: "Funcția reprezentantului",
    signer: "Semnatar",
    signedAt: "Data semnării",
    language: "Limba documentelor semnate",
    documents: "Copiile documentelor semnate",
    blocked: "Există documente semnate care necesită verificarea administratorului înainte de continuarea înscrierii. Documentele existente nu vor fi înlocuite.",
    reviewSaved: "Am găsit acordul salvat. Verifică datele juridice afișate, apoi apasă din nou butonul de trimitere pentru a continua cu acest acord.",
    signFirst: "Citește documentele, completează datele juridice și semnează înainte de trimitere.",
    signingFailed: "Semnarea nu a putut fi confirmată. Verifică datele și încearcă din nou.",
    verifyEmail: "Verifică adresa de e-mail a contului înainte de semnarea contractului.",
  },
  ru: {
    loading: "Проверяем ранее подписанные документы…",
    unavailable: "Не удалось проверить подписанные документы. Повторите проверку перед отправкой заявки.",
    retry: "Повторить проверку",
    title: "Продолжить с уже подписанным соглашением",
    intro: "Ваша подпись сохранена. Регистрация продолжится на основании документов ниже без новой подписи. Юридические реквизиты и язык договора остаются такими, какими они были при подписании, даже если вы сменили язык сайта.",
    correction: "Эти данные нельзя изменить здесь. Если сторона договора, идентификатор, адрес или представитель указаны неверно, не отправляйте заявку и обратитесь к администратору для исправления.",
    contact: "Связаться с администратором",
    party: "Физическое / юридическое лицо",
    kind: "Тип стороны",
    individual: "Физическое лицо",
    sole_trader: "Индивидуальный предприниматель",
    company: "Юридическое лицо",
    identifier: "IDNP / IDNO",
    address: "Юридический адрес",
    representative: "Представитель",
    role: "Должность представителя",
    signer: "Подписант",
    signedAt: "Дата подписания",
    language: "Язык подписанных документов",
    documents: "Копии подписанных документов",
    blocked: "Перед продолжением регистрации администратор должен проверить существующие подписанные документы. Они не будут заменены.",
    reviewSaved: "Найдено сохранённое соглашение. Проверьте отображаемые юридические реквизиты и ещё раз нажмите кнопку отправки, чтобы продолжить с этим соглашением.",
    signFirst: "Прочитайте документы, заполните юридические реквизиты и подпишите перед отправкой.",
    signingFailed: "Не удалось подтвердить подписание. Проверьте данные и попробуйте снова.",
    verifyEmail: "Подтвердите адрес электронной почты аккаунта перед подписанием договора.",
  },
  en: {
    loading: "Checking previously signed documents…",
    unavailable: "We could not verify your signed documents. Retry the check before submitting your registration.",
    retry: "Retry verification",
    title: "Continue with your saved agreement",
    intro: "Your signature has been saved. Registration will continue using the documents below without a new signature. The legal details and contract language remain as signed, even if you changed the site language.",
    correction: "These details cannot be edited here. If the contracting person or entity, identifier, address or representative is incorrect, do not submit your registration. Contact the administrator for a correction.",
    contact: "Contact the administrator",
    party: "Contracting person / entity",
    kind: "Party type",
    individual: "Individual",
    sole_trader: "Sole trader",
    company: "Company",
    identifier: "IDNP / IDNO",
    address: "Legal address",
    representative: "Representative",
    role: "Representative’s role",
    signer: "Signatory",
    signedAt: "Signing date",
    language: "Language of signed documents",
    documents: "Signed document copies",
    blocked: "An administrator must review your existing signed documents before registration can continue. Those documents will not be replaced.",
    reviewSaved: "We found your saved agreement. Review the displayed legal details, then press submit again to continue with this agreement.",
    signFirst: "Read the documents, complete the legal details and sign before submitting.",
    signingFailed: "We could not confirm the signature. Check your details and try again.",
    verifyEmail: "Verify your account email address before signing the contract.",
  },
} as const;
