// Exports a complete, portable copy of a PostgreSQL database: every enum,
// table, constraint, index, function and trigger, plus all rows.
//
// Written because this machine has no pg_dump (no Homebrew, and the Supabase
// CLI's dump path needs Docker). It reads the live catalog instead, and for
// indexes, constraints, functions and triggers it asks PostgreSQL for the
// exact definition rather than reconstructing one — pg_get_indexdef and its
// siblings are the same source pg_dump uses.
//
// The output is split so that data can load before the expensive and
// order-sensitive parts exist:
//
//   01-pre.sql    extensions, enums, tables, primary/unique keys
//   data/*.ndjson one file per table, one JSON row per line
//   02-post.sql   foreign keys, checks, indexes, functions, triggers
//   manifest.json table order, row counts, sequence positions
//
// Loading foreign keys after the rows removes every insertion-order problem
// without needing superuser (Supabase does not grant session_replication_role).
//
// Usage:
//   DATABASE_URL=… npx tsx scripts/db-export.ts <output-dir>

import "dotenv/config";
import { mkdirSync, writeFileSync, appendFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";

const outDir = process.argv[2];
if (!outDir) {
  console.error("Usage: npx tsx scripts/db-export.ts <output-dir>");
  process.exit(1);
}
const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is not set");
const sql = neon(url);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, "data"), { recursive: true });

const q = (s: string) => `"${s.replace(/"/g, '""')}"`;
const pre: string[] = [];
const post: string[] = [];
/** table -> column -> PostgreSQL type, so the importer can serialise a JSON
 *  array as JSON instead of letting the driver send a PostgreSQL array. */
const columnTypes: Record<string, Record<string, string>> = {};

async function main() {
pre.push("-- Generated by scripts/db-export.ts. Do not edit by hand.\n");

// ── extensions ───────────────────────────────────────────────────────
const exts = (await sql`
  SELECT extname FROM pg_extension
   WHERE extname <> 'plpgsql' ORDER BY extname`) as { extname: string }[];
for (const e of exts) {
  pre.push(`CREATE EXTENSION IF NOT EXISTS ${q(e.extname)};`);
}

// ── enum types, in dependency-free order ─────────────────────────────
// One row per label rather than array_agg: the HTTP driver hands arrays back
// as raw PostgreSQL array literals, and re-parsing those is a needless way to
// mangle a label containing a comma or a brace.
const enumRows = (await sql`
  SELECT t.typname, e.enumlabel
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
   WHERE n.nspname = 'public'
   ORDER BY t.typname, e.enumsortorder`) as
  { typname: string; enumlabel: string }[];
const enums = new Map<string, string[]>();
for (const r of enumRows) {
  const list = enums.get(r.typname) ?? [];
  list.push(r.enumlabel);
  enums.set(r.typname, list);
}
for (const [name, labels] of enums) {
  const vals = labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(", ");
  pre.push(`CREATE TYPE ${q(name)} AS ENUM (${vals});`);
}

// ── sequences ────────────────────────────────────────────────────────
// Before the tables, because a `serial` column's DEFAULT is
// nextval('…'::regclass) and that cast resolves at CREATE TABLE time — the
// table cannot be created until its sequence exists. Ownership is attached
// afterwards, once the owning column does.
const seqDefs = (await sql`
  SELECT sequencename, data_type::text AS data_type, start_value, min_value,
         max_value, increment_by, cycle, cache_size
    FROM pg_sequences
   WHERE schemaname = 'public'
   ORDER BY sequencename`) as {
  sequencename: string; data_type: string; start_value: string;
  min_value: string; max_value: string; increment_by: string;
  cycle: boolean; cache_size: string;
}[];
for (const s of seqDefs) {
  pre.push(
    `CREATE SEQUENCE ${q(s.sequencename)} AS ${s.data_type} ` +
      `INCREMENT BY ${s.increment_by} MINVALUE ${s.min_value} ` +
      `MAXVALUE ${s.max_value} START WITH ${s.start_value} ` +
      `CACHE ${s.cache_size}${s.cycle ? " CYCLE" : " NO CYCLE"};`,
  );
}

const owned = (await sql`
  SELECT s.relname AS seqname, t.relname AS tabname, a.attname AS colname
    FROM pg_class s
    JOIN pg_depend d ON d.objid = s.oid AND d.classid = 'pg_class'::regclass
    JOIN pg_class t ON t.oid = d.refobjid
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
    JOIN pg_namespace n ON n.oid = s.relnamespace
   WHERE s.relkind = 'S' AND n.nspname = 'public' AND d.deptype = 'a'
   ORDER BY s.relname`) as
  { seqname: string; tabname: string; colname: string }[];

// ── tables ───────────────────────────────────────────────────────────
const tables = (await sql`
  SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind = 'r'
   ORDER BY c.relname`) as { relname: string }[];

for (const { relname } of tables) {
  const cols = (await sql`
    SELECT a.attname,
           format_type(a.atttypid, a.atttypmod) AS coltype,
           a.attnotnull,
           pg_get_expr(d.adbin, d.adrelid) AS coldefault,
           a.attidentity,
           a.attgenerated
      FROM pg_attribute a
      LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
     WHERE a.attrelid = ${`public.${relname}`}::regclass
       AND a.attnum > 0 AND NOT a.attisdropped
     ORDER BY a.attnum`) as {
    attname: string; coltype: string; attnotnull: boolean;
    coldefault: string | null; attidentity: string; attgenerated: string;
  }[];

  columnTypes[relname] = Object.fromEntries(
    cols.map((c) => [c.attname, c.coltype]),
  );
  const lines = cols.map((c) => {
    let s = `  ${q(c.attname)} ${c.coltype}`;
    if (c.attidentity === "a") s += " GENERATED ALWAYS AS IDENTITY";
    else if (c.attidentity === "d") s += " GENERATED BY DEFAULT AS IDENTITY";
    else if (c.coldefault && !c.attgenerated) s += ` DEFAULT ${c.coldefault}`;
    if (c.attnotnull) s += " NOT NULL";
    return s;
  });
  pre.push(`\nCREATE TABLE ${q(relname)} (\n${lines.join(",\n")}\n);`);
}

// Sequence ownership, now that the owning columns exist. Without this a
// dropped table leaves its sequence behind.
for (const o of owned) {
  pre.push(
    `ALTER SEQUENCE ${q(o.seqname)} OWNED BY ${q(o.tabname)}.${q(o.colname)};`,
  );
}

// ── constraints: p/u go before the data, f/c after it ────────────────
const cons = (await sql`
  SELECT c.conname, c.contype, rel.relname,
         pg_get_constraintdef(c.oid) AS def
    FROM pg_constraint c
    JOIN pg_class rel ON rel.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = rel.relnamespace
   WHERE n.nspname = 'public'
   ORDER BY c.contype, c.conname`) as {
  conname: string; contype: string; relname: string; def: string;
}[];
for (const c of cons) {
  const stmt = `ALTER TABLE ${q(c.relname)} ADD CONSTRAINT ${q(c.conname)} ${c.def};`;
  (c.contype === "p" || c.contype === "u" ? pre : post).push(stmt);
}

// ── indexes that no constraint already created ───────────────────────
const idx = (await sql`
  SELECT i.indexname, i.indexdef
    FROM pg_indexes i
   WHERE i.schemaname = 'public'
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint c WHERE c.conname = i.indexname
     )
   ORDER BY i.indexname`) as { indexname: string; indexdef: string }[];
for (const i of idx) post.push(`${i.indexdef};`);

// ── functions, then the triggers that call them ──────────────────────
const fns = (await sql`
  SELECT pg_get_functiondef(p.oid) AS def
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.prokind = 'f'
   ORDER BY p.proname`) as { def: string }[];
for (const f of fns) post.push(`${f.def};`);

const trgs = (await sql`
  SELECT pg_get_triggerdef(t.oid) AS def
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND NOT t.tgisinternal
   ORDER BY t.tgname`) as { def: string }[];
for (const t of trgs) post.push(`${t.def};`);

// ── rows ─────────────────────────────────────────────────────────────
const counts: Record<string, number> = {};
for (const { relname } of tables) {
  // Every column as text, exactly as PostgreSQL renders it. Letting the
  // driver parse values first is how a migration silently corrupts data: a
  // `timestamp` becomes a JS Date, JSON.stringify writes it back as UTC, and
  // the row lands three hours off with its microseconds truncated to
  // milliseconds. A date column shifts by a whole day the same way. Text in,
  // text out — PostgreSQL parses its own output back losslessly.
  const colNames = Object.keys(columnTypes[relname]);
  const selectList = colNames
    .map((c) => `${q(c)}::text AS ${q(c)}`)
    .join(", ");
  const rows = (await sql.query(
    `SELECT ${selectList} FROM ${q(relname)}`,
  )) as Record<string, unknown>[];
  counts[relname] = rows.length;
  const file = join(outDir, "data", `${relname}.ndjson`);
  writeFileSync(file, "");
  for (const r of rows) appendFileSync(file, JSON.stringify(r) + "\n");
}

// ── sequence positions, so the next insert does not collide ──────────
const seqs = (await sql`
  SELECT sequence_name FROM information_schema.sequences
   WHERE sequence_schema = 'public' ORDER BY sequence_name`) as
  { sequence_name: string }[];
const seqValues: Record<string, string> = {};
for (const s of seqs) {
  const r = (await sql.query(
    `SELECT last_value, is_called FROM ${q(s.sequence_name)}`,
  )) as { last_value: string; is_called: boolean }[];
  seqValues[s.sequence_name] = `${r[0].last_value}:${r[0].is_called}`;
}

writeFileSync(join(outDir, "01-pre.sql"), pre.join("\n") + "\n");
writeFileSync(join(outDir, "02-post.sql"), post.join("\n") + "\n");
writeFileSync(
  join(outDir, "manifest.json"),
  JSON.stringify(
    {
      exportedFrom: (url as string).replace(/:[^:@]+@/, ":***@"),
      tables: tables.map((t) => t.relname),
      columnTypes,
      enums: enums.size,
      counts,
      sequences: seqValues,
      totalRows: Object.values(counts).reduce((a, b) => a + b, 0),
    },
    null,
    2,
  ) + "\n",
);

console.log(
  `Exported ${tables.length} tables, ${enums.size} enums, ` +
    `${Object.values(counts).reduce((a, b) => a + b, 0)} rows → ${outDir}`,
);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
